name: Build and run kernels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run-kernels:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Install CIRCT
        uses: circt/install-circt@v1.1.1
        with:
          # The version of CIRCT to install.  This must match a release of CIRCT,
          # e.g., 'firtool-1.56.1' or one of the following special strings:
          #   - 'nightly' installs the latest nightly
          #   - 'version-file' installs the release specified by a JSON file whose
          #     location is set by the 'version-file' input.  This is done to
          #     facilitate Continuous Delivery (CD) flows because GitHub Actions are
          #     not allowed to modify anything in the '.github/' directory.
          #
          # Default: 'version-file'
          version: 'firtool-1.62.0'
      - name: Get snax_cluster submodule commit hash
        id: get-submodule-commit
        run: |
          cd snax_cluster
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ steps.get-submodule-commit.outputs.commit_hash }}
      - name: Build and run kernels
        run: pixi run snakemake -k -p -j `nproc` all
        working-directory: kernels/${{ matrix.kernel }}
    strategy:
      matrix:
        kernel: [streamer_matmul]
